name: Build and Upload OpenCore-Patcher.app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code from specified repository
        run: |
          git clone https://github.com/Kuroshimacat/OpenCore-Legacy-Patcher.git ~/Developer/OpenCore-Legacy-Patcher
          cd /Users/runner/Developer/OpenCore-Legacy-Patcher
          python3 -m venv venv
          source venv/bin/activate
          pip install pyinstaller
          pip install requests
          pip install pyobjc
          pip install wxpython
          pip install pyinstaller
          pip install packaging
          pip install py_sip_xnu
          pip install py-applescript
          pip install markdown2
          pip install macos-pkg-builder
          pip install mac-signing-buddy
          pyinstaller --target-arch=x86_64 OpenCore-Patcher-GUI.spec
          python3 Build-Project.command

      - name: Upload OpenCore-Patcher.app as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher
          path: ~/Developer/OpenCore-Legacy-Patcher/dist/OpenCore-Patcher.app
