name: Build and Upload OpenCore-Patcher.app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code from specified repository
        run: |
          git clone https://github.com/Kuroshimacat/OpenCore-Legacy-Patcher.git ~/Developer/OpenCore-Legacy-Patcher

      - name: Create and activate virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
        working-directory: ~/Developer/OpenCore-Legacy-Patcher

      - name: Install PyInstaller
        run: |
          pip install pyinstaller requests pyobjc wxpython pyinstaller packaging py_sip_xnu py-applescript markdown2 macos-pkg-builder mac-signing-buddy

      - name: Create the pyinstaller based Application
        run: |
          python3 Build-Project.command

      - name: Upload OpenCore-Patcher.app as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenCore-Patcher
          path: ~/Developer/OpenCore-Legacy-Patcher/dist/OpenCore-Patcher.app
